<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="BikramKarisMini" failures="2" tests="12" name="Test2" time="122.887" errors="0" timestamp="2024-07-01T17:17:54 IST">
  <testcase classname="com.akhilsystem_release.test.emr.VisitWiseWebpart" name="openAppointment" time="8.792"/>
  <testcase classname="com.akhilsystem_release.test.emr.VisitWiseWebpart" name="firstDoctor" time="19.003"/>
  <testcase classname="com.akhilsystem_release.test.emr.VisitWiseWebpart" name="secondDoctor" time="15.042"/>
  <testcase classname="com.akhilsystem_release.test.emr.VisitWiseWebpart" name="thirdDoctor" time="15.917"/>
  <testcase classname="com.akhilsystem_release.test.emr.VisitWiseWebpart" name="closeAppointment" time="3.075"/>
  <testcase classname="com.akhilsystem_release.test.emr.VisitWiseWebpart" name="fstDoctorLogin" time="12.131"/>
  <testcase classname="com.akhilsystem_release.test.emr.VisitWiseWebpart" name="fillFstDoctorData" time="6.449">
    <failure type="com.akhilsystem_release.base.Base$CustomException" message="Data not updated successfully. Expected message: &amp;apos;Updated Successfully&amp;apos;, but received: ">
      <![CDATA[com.akhilsystem_release.base.Base$CustomException: Data not updated successfully. Expected message: 'Updated Successfully', but received: 
at com.akhilsystem_release.test.emr.VisitWiseWebpart.fillFstDoctorData(VisitWiseWebpart.java:144)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- fillFstDoctorData -->
  <testcase classname="com.akhilsystem_release.test.emr.VisitWiseWebpart" name="sndDoctorLogin" time="10.645"/>
  <testcase classname="com.akhilsystem_release.test.emr.VisitWiseWebpart" name="verifyFstDoctorData" time="3.312">
    <failure type="java.lang.AssertionError" message="expected [1729] but found [361210]">
      <![CDATA[java.lang.AssertionError: expected [1729] but found [361210]
at com.akhilsystem_release.test.emr.VisitWiseWebpart.verifyFstDoctorData(VisitWiseWebpart.java:161)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- verifyFstDoctorData -->
  <testcase classname="com.akhilsystem_release.test.emr.VisitWiseWebpart" name="fillSndDoctorData" time="3.559"/>
  <testcase classname="com.akhilsystem_release.test.emr.VisitWiseWebpart" name="trdDoctorLogin" time="11.097"/>
  <testcase classname="com.akhilsystem_release.test.emr.VisitWiseWebpart" name="verifySndDoctorData" time="4.312"/>
</testsuite> <!-- Test2 -->
